### ISSUE TITLE
How to get as a png?

### ISSUE THREAD

**Issue by CaoTrongThang** [solstice23/osu-stats-signature#6]
I want to get the card but as png link, how can i do that?, thanks

**Comment by solstice23** [comment]
Cards are generated as SVG. It doesn't matter because you can use SVG just like PNG. Every modern browser supports it.

If you want to get a PNG copy of the signature for posting on social media, you can right click on the card and select "Copy Image", it will be automatically converted to PNG format in your clipboard.

If you really want to GENERATE AN PNG for some specific usages, maybe I can implement it (really depends on whether I have spare time and motivation). I strongly don't recommend this, because some features such as animations can only be presented in SVG rather than in a static image, and SVGs usually take up smaller file sizes. So I must make lots of effort to cope with these new problems.

**Comment by CaoTrongThang** [comment]
I mean I just wanna use it as a png url for my discord bot, it looks really cool, but if it needs alot of effort for you to do then I'll find other ways.

**Comment by solstice23** [comment]
You can fork this and make your own version for the bot. There are lots of libraries to convert PNG to SVG on npm. It's hard to implement it without conflicting with these various options. But for your own fork, you can generate PNGs with specific and limited option sets, so that these conflicts can be ignored.

**Comment by CaoTrongThang** [comment]
> You can fork this and make your own version for the bot. There are lots of libraries to convert PNG to SVG on npm. It's hard to implement it without conflicting with these various options. But for your own fork, you can generate PNGs with specific and limited option sets, so that these conflicts can be ignored.

It's kinda hard for a new programmer like me can do things like that, I'm trying to find a way to convert the Osu! skills to png with Java but it's kinda no hope.
![image](https://user-images.githubusercontent.com/51023235/196044806-c30990eb-a69e-4204-bad2-c429102ad6dd.png)

**Comment by CaoTrongThang** [comment]
I don't even know how you can calculate the skills stats

**Comment by solstice23** [comment]
This program doesn't calculate skills stats, it retrieves data from osu! Skills website.

**Comment by solstice23** [comment]
And you can convert it to PNG via node or java. Depends on which one you are more familiar with.

**Comment by CaoTrongThang** [comment]
> And you can convert it to PNG via node or java. Depends on which one you are more familiar with.

I mean i'll try my best to make a skills stats png, but really hope you will add that feature in the future.

**Comment by solstice23** [comment]
It's kanda of hard to maintain the project in the future if I added this conversion feature. But I can help you on your fork.

**Comment by CaoTrongThang** [comment]
> 

Believe me, mate, it's way better to make that feature yourself instead of helping me, I'm a so new programmer, don't waste any time on me. Thanks for your time bro.
